name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

  build-binaries:
    name: Build Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
            suffix: ''
          - os: macos-latest
            target: x86_64-apple-darwin
            suffix: ''
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    - name: Build binary
      run: cargo build --release --target ${{ matrix.target }} --bin bitnet-cli
    
    - name: Package binary
      run: |
        cd target/${{ matrix.target }}/release
        tar -czf bitnet-${{ matrix.target }}.tar.gz bitnet-cli${{ matrix.suffix }}
    
    - name: Upload binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: target/${{ matrix.target }}/release/bitnet-${{ matrix.target }}.tar.gz
        asset_name: bitnet-${{ matrix.target }}.tar.gz
        asset_content_type: application/gzip