[target.aarch64-apple-darwin]
rustflags = [
    "-C", "target-cpu=native",
    "-C", "target-feature=+neon"
]

[target.x86_64-apple-darwin]
rustflags = [
    "-C", "target-cpu=native", 
    "-C", "target-feature=+avx2,+fma"
]

[profile.dev]
lto = false

[profile.release]
lto = true
opt-level = 3